// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa_1s5_rYrVliHr2PyG5tB249zywY2gkI',
    appId: '1:641663905277:web:dbc2ac759ad522b7963d94',
    messagingSenderId: '641663905277',
    projectId: 'todo-firebase-app-1f9a9',
    authDomain: 'todo-firebase-app-1f9a9.firebaseapp.com',
    storageBucket: 'todo-firebase-app-1f9a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdoohe-5xqwOTGon4uXNiy5Y2r83ekzOU',
    appId: '1:641663905277:android:1646943b35d2e0b7963d94',
    messagingSenderId: '641663905277',
    projectId: 'todo-firebase-app-1f9a9',
    storageBucket: 'todo-firebase-app-1f9a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYok2pSJ1QXdPuGzWqqM41gNnov0lFKIQ',
    appId: '1:641663905277:ios:4ccb9831b081777f963d94',
    messagingSenderId: '641663905277',
    projectId: 'todo-firebase-app-1f9a9',
    storageBucket: 'todo-firebase-app-1f9a9.firebasestorage.app',
    iosBundleId: 'com.example.todoFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYok2pSJ1QXdPuGzWqqM41gNnov0lFKIQ',
    appId: '1:641663905277:ios:4ccb9831b081777f963d94',
    messagingSenderId: '641663905277',
    projectId: 'todo-firebase-app-1f9a9',
    storageBucket: 'todo-firebase-app-1f9a9.firebasestorage.app',
    iosBundleId: 'com.example.todoFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa_1s5_rYrVliHr2PyG5tB249zywY2gkI',
    appId: '1:641663905277:web:ed26fd4d2ec55a0c963d94',
    messagingSenderId: '641663905277',
    projectId: 'todo-firebase-app-1f9a9',
    authDomain: 'todo-firebase-app-1f9a9.firebaseapp.com',
    storageBucket: 'todo-firebase-app-1f9a9.firebasestorage.app',
  );
}
